/*
 * Test.java
 *
 * Created on __DATE__, __TIME__
 */

package org.gfg.dartearth.core;

import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.layers.Layer;
import gov.nasa.worldwind.layers.LayerList;
import gov.nasa.worldwind.layers.TerrainProfileLayer;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

import org.gfg.metadata.ESQuery;
import org.gfg.metadata.model.ESearchField;

/**
 * 
 * @author __USER__
 */
public class MetaDataSearchUI extends JDialog {

	private WorldWindow wwd;
	/** Creates new form Test */
	public MetaDataSearchUI(java.awt.Frame parent, boolean modal,
			WorldWindow wwd) {
		super(parent, modal);
		this.wwd = wwd;
		initComponents();
		this.setLocation(170, 70);
		this.setSize(400, 900);
		this.setTitle("卫星数据获取");
		// this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		bgPanel = new javax.swing.JPanel();
		contidionPanel = new javax.swing.JPanel();
		statelliteLabel = new javax.swing.JLabel();
		statelliteComboBox = new javax.swing.JComboBox();
		sensorLabel = new javax.swing.JLabel();
		sensorComboBox = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		neveralComboBox = new javax.swing.JComboBox();
		productLevelLabel = new javax.swing.JLabel();
		productLevelComboBox = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		beginTimeText = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		endTimeText = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		productIdText = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		senceIdText = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		averageCloudText = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		search = new javax.swing.JButton();
		resultPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		retList = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		statelliteLabel.setText("\u536b\u661f   \uff1a");

		statelliteComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "", "GF1", "GF2", "HJ1A", "HJ1B" }));

		sensorLabel.setText("\u4f20\u611f\u5668    \uff1a");

		sensorComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "", "PMS1", "PMS2", "WFV1", "WFV2", "WFV3",
						"WFV4", "IRS", "MUX", "PAN1", "MSS1", "MSS2", "CCD1",
						"CCD2", "HSI" }));

		jLabel2.setText("\u5206\u8fa8\u7387\uff1a");

		neveralComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "", "2", "8", "16"}));

		productLevelLabel.setText("\u6570\u636e\u7ea7\u522b\uff1a");

		productLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "", "LEVEL0_SCENE", "LEVEL1A", "LEVEL2A" }));

		jLabel4.setText("\u5f00\u59cb\u65f6\u95f4\uff1a");

		jLabel5.setText("\u7ed3\u675f\u65f6\u95f4\uff1a");

		jLabel6.setText("\u4ea7\u54c1\u53f7\uff1a");

		jLabel7.setText("\u666f\u53f7\uff1a");

		jLabel8.setText("\u4e91\u91cf\u5c0f\u4e8e\uff1a");

		jLabel9.setText("%");

		search.setText("\u641c\u7d22");
		search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout contidionPanelLayout = new javax.swing.GroupLayout(
				contidionPanel);
		contidionPanel.setLayout(contidionPanelLayout);
		contidionPanelLayout
				.setHorizontalGroup(contidionPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								contidionPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																contidionPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				contidionPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								contidionPanelLayout
																										.createSequentialGroup()
																										.addGroup(
																												contidionPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																statelliteLabel))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												contidionPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																neveralComboBox,
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																statelliteComboBox,
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																0,
																																86,
																																Short.MAX_VALUE))
																										.addGroup(
																												contidionPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																contidionPanelLayout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				sensorLabel))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																contidionPanelLayout
																																		.createSequentialGroup()
																																		.addGap(9,
																																				9,
																																				9)
																																		.addComponent(
																																				productLevelLabel)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												contidionPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																productLevelComboBox,
																																0,
																																119,
																																Short.MAX_VALUE)
																														.addComponent(
																																sensorComboBox,
																																0,
																																119,
																																Short.MAX_VALUE)))
																						.addGroup(
																								contidionPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel6)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												productIdText,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												75,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel7)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												senceIdText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												163,
																												Short.MAX_VALUE)))
																		.addGap(43,
																				43,
																				43))
														.addGroup(
																contidionPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				contidionPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								contidionPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												beginTimeText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												280,
																												Short.MAX_VALUE))
																						.addGroup(
																								contidionPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												endTimeText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												280,
																												Short.MAX_VALUE)))
																		.addGap(43,
																				43,
																				43))
														.addGroup(
																contidionPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				averageCloudText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel9)
																		.addContainerGap())
														.addGroup(
																contidionPanelLayout
																		.createSequentialGroup()
																		.addGap(115,
																				115,
																				115)
																		.addComponent(
																				search,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				124,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap()))));
		contidionPanelLayout
				.setVerticalGroup(contidionPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								contidionPanelLayout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																sensorLabel)
														.addComponent(
																statelliteLabel)
														.addComponent(
																statelliteComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																sensorComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																productLevelLabel)
														.addComponent(
																neveralComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																productLevelComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																productIdText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																senceIdText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																beginTimeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																endTimeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												contidionPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9)
														.addComponent(
																averageCloudText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												search,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		DefaultListModel listModel = new DefaultListModel();
		listModel = getListModel();
		retList.setModel(listModel);
		retList.setFixedCellHeight(120);

		// retList.setFixedCellWidth(100);
		retList.setCellRenderer(new MetaDataCellRenderer());
		jScrollPane1.setViewportView(retList);
		retList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				retListMouseClicked(evt);
			}
		});
		javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(
				resultPanel);
		resultPanel.setLayout(resultPanelLayout);
		resultPanelLayout
				.setHorizontalGroup(resultPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								resultPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												389, Short.MAX_VALUE)
										.addContainerGap()));
		resultPanelLayout
				.setVerticalGroup(resultPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								resultPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												621, Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(
				bgPanel);
		bgPanel.setLayout(bgPanelLayout);
		bgPanelLayout.setHorizontalGroup(bgPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(contidionPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(resultPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		bgPanelLayout
				.setVerticalGroup(bgPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								bgPanelLayout
										.createSequentialGroup()
										.addComponent(
												contidionPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												resultPanel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addComponent(bgPanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				bgPanel, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void retListMouseClicked(java.awt.event.MouseEvent e) {
		if (e.getButton() == 1) {
			System.out.println(retList.getSelectedValue());
			Map<String,Object> recordMap = (Map)retList.getSelectedValue();
			for(String key:recordMap.keySet()){
				System.out.println(key + "--->"+recordMap.get(key));
			}
			// 根据从map中获取到的值拼接处该层的名称格式为GF1_PMS1_20140706_0000032332
			//卫星名_传感器_时间产品id
			String showLayerName =recordMap.get(ESearchField._ID.getField()).toString();
			System.out.println("show layer name: " + showLayerName);
			//TODO 
			final Map<String, Layer> showLayer = new HashMap<String, Layer>();
			LayerList layerList = wwd.getModel().getLayers();
			for (Layer layer : layerList) {
				if (layer instanceof TerrainProfileLayer) {
					continue;
				}
				String layerName = layer.getName();
				if (layerName.matches("GF\\w*_\\w*_\\w*")) {
					showLayer.put(layerName, layer);
				}
			}
			for(String key:showLayer.keySet()){
				if(key.equals(showLayerName)){
					System.out.println("show layer name: " + showLayerName + " true");
					showLayer.get(key).setEnabled(true);
					System.out.println("------------");
				}else{
					showLayer.get(key).setEnabled(false);
				}
			}
			wwd.redraw();
			//JOptionPane.showMessageDialog(this, "左键");
		}
		else if (e.getButton() == 3) {
			//JOptionPane.showMessageDialog(this, "右键");
			//TODO  下载实体数据
		}
	}

	private DefaultListModel getListModel() {
		DefaultListModel listModel = new DefaultListModel();
		ESQuery query = new ESQuery();
		Map<String, Object> conditionMap = new HashMap<String, Object>();
		List<Map<String, Object>> listMap = query
				.queryByMultipleContidion(conditionMap);
		// for (Map<String, Object> map : listMap) {
		// listModel.addElement(map.get(ESearchField.SATELLITENAME.getField())
		// + "---" + map.get(ESearchField.SENSOR.getField()) + "---"
		// + map.get(ESearchField.PRODUCTID.getField()));
		// }
		for (Map<String, Object> map : listMap) {
			listModel.addElement(map);
		}
		return listModel;
	}

	private void searchActionPerformed(java.awt.event.ActionEvent evt) {
		DefaultListModel listModel = new DefaultListModel();

		Map<String, Object> conditionMap = new HashMap<String, Object>();
		if (statelliteComboBox.getSelectedItem().toString() != null
				&& statelliteComboBox.getSelectedItem().toString().length() > 0) {

			String statellite = statelliteComboBox.getSelectedItem().toString();
			conditionMap.put(ESearchField.SATELLITENAME.getField(), statellite);
		}
		if (sensorComboBox.getSelectedItem().toString() != null
				&& sensorComboBox.getSelectedItem().toString().length() > 0) {
			String sensor = sensorComboBox.getSelectedItem().toString();
			conditionMap.put(ESearchField.SENSOR.getField(), sensor);
		}
		if (productLevelComboBox.getSelectedItem() != null
				&& productLevelComboBox.getSelectedItem().toString().length() > 0) {

			String productLevel = productLevelComboBox.getSelectedItem()
					.toString();
			conditionMap
					.put(ESearchField.PRODUCTLEVEL.getField(), productLevel);
		}
		if (neveralComboBox.getSelectedItem() != null
				&& neveralComboBox.getSelectedItem().toString().length() > 0) {
			Double neveral = Double.parseDouble(neveralComboBox
					.getSelectedItem().toString());
			conditionMap.put(ESearchField.NRESVAL.getField(), neveral);
		}

		if (productIdText.getText().length() > 0
				&& productIdText.getText() != "") {
			String productId = productIdText.getText();
			conditionMap.put(ESearchField.PRODUCTID.getField(), productId);

		}
		// System.out.println(senceIdText.getText());
		if (senceIdText.getText() != null && senceIdText.getText() != ""
				&& senceIdText.getText().length() > 0) {
			Long senceId = Long.parseLong(senceIdText.getText());
			conditionMap.put(ESearchField.SCENEID.getField(), senceId);
		}
		if (beginTimeText.getText().length() > 0
				&& endTimeText.getText().length() > 0
				&& beginTimeText.getText() != "" && endTimeText.getText() != "") {
			String beginTime = beginTimeText.getText();
			String endTime = endTimeText.getText();
			conditionMap
					.put(ESearchField.FROMPRODUCTDATE.getField(), beginTime);
			conditionMap.put(ESearchField.TOPRODUCTDATE.getField(), endTime);

		}
		if (averageCloudText.getText() != null
				&& averageCloudText.getText().length() > 0) {
			Double cloud = Double.parseDouble(averageCloudText.getText()
					.toString());
			conditionMap.put(ESearchField.AVGCLOUDCOVER.getField(), cloud);
		}
		ESQuery query = new ESQuery();
		List<Map<String, Object>> listMap = query
				.queryByMultipleContidion(conditionMap);
		for (Map<String, Object> map : listMap) {
			// listModel.addElement(map.get(ESearchField.SATELLITENAME.getField())
			// + "---" + map.get(ESearchField.SENSOR.getField()) + "---"
			// + map.get(ESearchField.PRODUCTID.getField()));
			listModel.addElement(map);
		}
		retList.setModel(listModel);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		MetaDataSearchUI dialog = new MetaDataSearchUI(new JFrame(), false,
				null);
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent e) {
				// System.exit(0);
			}
		});
		dialog.setVisible(true);
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel bgPanel;
	private javax.swing.JPanel contidionPanel;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox neveralComboBox;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	@SuppressWarnings("rawtypes")
	private javax.swing.JList retList;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField beginTimeText;
	private javax.swing.JTextField endTimeText;
	private javax.swing.JTextField productIdText;
	private javax.swing.JTextField senceIdText;
	private javax.swing.JTextField averageCloudText;
	private javax.swing.JComboBox productLevelComboBox;
	private javax.swing.JLabel productLevelLabel;
	private javax.swing.JPanel resultPanel;
	private javax.swing.JButton search;
	private javax.swing.JComboBox sensorComboBox;
	private javax.swing.JLabel sensorLabel;
	private javax.swing.JComboBox statelliteComboBox;
	private javax.swing.JLabel statelliteLabel;
	// End of variables declaration//GEN-END:variables

}